name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using OpenAI or Deepseek API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  API_PROVIDER:
    description: "API provider to use for code review (openai or deepseek)."
    required: false
    default: "openai"
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT (required if API_PROVIDER is openai)."
    required: false
  OPENAI_API_MODEL:
    description: "OpenAI API model."
    required: false
    default: ""
  DEEPSEEK_API_KEY:
    description: "Deepseek API key (required if API_PROVIDER is deepseek)."
    required: false
  DEEPSEEK_API_MODEL:
    description: "Deepseek API model."
    required: false
    default: ""
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
  REVIEW_MODE:
    description: "Review mode: 'default', 'single_commit', or 'commit_range'"
    required: false
    default: "default"
  COMMIT_SHA:
    description: "SHA of the commit to review when REVIEW_MODE is 'single_commit'"
    required: false
    default: ""
  BASE_SHA:
    description: "Base SHA for commit range review when REVIEW_MODE is 'commit_range'"
    required: false
    default: ""
  HEAD_SHA:
    description: "Head SHA for commit range review when REVIEW_MODE is 'commit_range'"
    required: false
    default: ""
  ALLOWED_USERS:
    description: "Comma-separated list of GitHub usernames allowed to trigger reviews via comments"
    required: false
    default: ""
  STYLE_GUIDE_URL:
    description: "URL to a GitHub-hosted style guide for documentation (e.g., https://github.com/pingcap/docs-cn/blob/master/resources/pingcap-style-guide-zh.pdf)"
    required: false
    default: ""
  TERMS_GUIDE_URL:
    description: "URL to a GitHub-hosted terms glossary for documentation (e.g., https://github.com/pingcap/docs-cn/blob/master/resources/tidb-terms.md)"
    required: false
    default: ""
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
